defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts"
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile

kramdown:
  input: GFM

timezone: "America/Montreal"
